### ISSUE TITLE
Fix pls

### ISSUE THREAD

**Issue by nzAily** [Mrchlldev/MCrates#2]
Fatal error: Declaration of Mrchlldev\MCrates\tiles\CrateTile::addAdditionalSpawnData(pocketmine\nbt\tag\CompoundTag $nbt): void must be compatible with pocketmine\block\tile\Chest::addAdditionalSpawnData(pocketmine\nbt\tag\CompoundTag $nbt, pocketmine\network\mcpe\convert\TypeConverter $typeConverter): void in /home/container/plugins/1Creat/src/Mrchlldev/MCrates/tiles/CrateTile.php on line 160

**Comment by Mrchlldev** [comment]
are you use PocketMine-MP by Nethergames?

**Comment by nzAily** [comment]
> are you use PocketMine-MP by Nethergames?

sure

**Comment by Mrchlldev** [comment]
goto the Mrchlldev\MCrates\tiles\CrateTile.php

add this before "class CrateTile extends Chest;" :
use pocketmine\network\mcpe\convert\TypeConverter;

now goto the line 160
change :
public function addAdditionalSpawnData(CompoundTag $nbt): void

to:
public function addAdditionalSpawnData(CompoundTag $nbt, TypeConverter $typeConverter): void

if you have done, you can restart your server.

**Comment by nzAily** [comment]
> goto the Mrchlldev\MCrates\tiles\CrateTile.php
> 
> add this before "class CrateTile extends Chest;" : use pocketmine\network\mcpe\convert\TypeConverter;
> 
> now goto the line 160 change : public function addAdditionalSpawnData(CompoundTag $nbt): void
> 
> to: public function addAdditionalSpawnData(CompoundTag $nbt, TypeConverter $typeConverter): void
> 
> if you have done, you can restart your server.

When creating create appears
 [02:36:10.379] [Server thread/EMERGENCY]: Crash occurred while handling a packet from session: Player [02:36:10.380] [Server thread/CRITICAL]: ArgumentCountError: "Too few arguments to function pocketmine\block\tile\Chest::addAdditionalSpawnData(), 1 passed in C:\Users\Asus\Documents\PM\plugins\MCrates\src\Mrchlldev\MCrates\tiles\CrateTile.php on line 163 and exactly 2 expected" (EXCEPTION) in "pmsrc/src/block/tile/Chest" at line 217

**Comment by Mrchlldev** [comment]
try to change
class CrateTile extends Chest

to
class CrateTile

**Comment by nzAily** [comment]
> try to change class CrateTile extends Chest
> 
> to class CrateTile

Fatal error: Cannot use "parent" when current class scope has no parent in C:\Users\Asus\Documents\PM\plugins\MCrates\src\Mrchlldev\MCrates\tiles\CrateTile.php on line 41
If you change it, this is what will appear

**Comment by Mrchlldev** [comment]
i don't know about your software, because i use the PocketMine-MP software originally.

**Comment by nzAily** [comment]
> i don't know about your software, because i use the PocketMine-MP software originally.

ok never mind, but i thank you for your suggestion above, because of that i managed to fix it :)
i will close this forum
